name: CI Test

on:
  push: []

jobs:
  test-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo --color always test

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo --color always test
